package net.postchain.rell.codegen

import assertk.all
import assertk.assertions.startsWith
import org.junit.jupiter.api.Test
import assertk.assert
import assertk.assertions.contains
import assertk.assertions.hasSize
import net.postchain.rell.codegen.document.AbstractDocument
import net.postchain.rell.codegen.section.Entity

internal class AbstractDocumentTest{

    @Test
    fun `Dummy objects are formatted properly`() {
        val doc = TestDocument()
        doc.addSection(TestEntity("MyEntity", listOf("import1", "import2")))
        doc.addSection(TestEntity("YourEntity", listOf("import1")))

        val formatted = doc.format()
        println(formatted)

        //Assert startswith intro and package
        assert(formatted).all {
            startsWith("//")
            contains("import2")
            contains("MyEntity")
        }
        // Assert contains import1 ONCE
        assert(formatted.split("import1")).hasSize(2)
    }

}

class TestDocument : AbstractDocument("// Generated by codegen", "package net.postchain.test")

class TestEntity(override val name: String, override val imports: List<String> = listOf()) : Entity {
    override val externalName = name
    override val moduleName = "test"
    override fun format(): String = name
}