// Generated by javascript generator

export function assertNumber(arg) {
	if(typeof arg !== "number") throw new Error("Expected input to be number")
}

export function assertBigInteger(arg) {
	if(typeof arg !== "bigint") throw new Error("Expected input to be bigint")
}

export function assertString(arg) {
	if(typeof arg !== "string") throw new Error("Expected input to be string")
}

export function assertObject(arg) {
	if(typeof arg !== "object") throw new Error("Expected input to be object")
}

export function assertBuffer(arg) {
	if(!(arg instanceof Buffer)) throw new Error("Expected input to be Buffer")
}

export function assertSet(arg) {
	if(!(arg instanceof Set)) throw new Error("Expected input to be Set")
}

export function assertArray(arg) {
	if(!(arg instanceof Array)) throw new Error("Expected input to be Array")
}

/* Unsupported Rell type for JS assertion, defaults to true */
export function assertAny(arg) {
	return true
}
