image: eclipse-temurin:21-jdk-noble

stages:
  - build
  - deploy
  - dependency-check

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.caching=true"
  POSTCHAIN_DB_URL: jdbc:postgresql://docker/postchain
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""
  TESTCONTAINERS_HOST_OVERRIDE: docker
  TESTCONTAINERS_RYUK_DISABLED: "true"
  JACOCO_REPORT_DIR: coverage-report-aggregate/build/reports/jacoco/testCodeCoverageReport

services:
  - name: docker:28-dind
    alias: docker
    command: [ "--tls=false" ]

cache:
  key: "$CI_COMMIT_REF_SLUG"
  fallback_keys:
    - dev
  paths:
    - .gradle
  policy: pull-push

.setup:
  tags: [ saas-linux-xlarge-amd64 ]
  before_script:
    - apt-get update && apt-get install -y ca-certificates curl gnupg jq
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu noble stable" > /etc/apt/sources.list.d/docker.list
    - apt-get update && apt-get install -y docker-ce-cli
    - docker run
      --detach
      --name postgres
      --env POSTGRES_PASSWORD=postchain
      --env POSTGRES_USER=postchain
      --env PGDATA=/pgtmpfs
      --tmpfs=/pgtmpfs:size=1000m
      --publish 5432:5432
      postgres:16.13-alpine3.23@sha256:20edbde7749f822887a1a022ad526fde0a47d6b2be9a8364433605cf65099416
    - chmod +x gradlew
    - ./gradlew --version
  artifacts:
    when: always
    paths:
      - $JACOCO_REPORT_DIR/*
      - "**/build/test-results/**/*"
    reports:
      junit: [ "**/build/test-results/**/TEST-*.xml" ]
      coverage_report:
        coverage_format: jacoco
        path: "**/build/reports/jacoco/test/jacocoTestReport.xml"
    expire_in: 1 week

build:
  extends: .setup
  stage: build
  except:
    - master
    - dev
    - /^version-[0-9]+[.][0-9]+([.][0-9]+)?$/
  script: [ "./gradlew check :coverage-report-aggregate:testCodeCoverageReport" ]

deploy:
  extends: .setup
  stage: deploy
  only:
    - master
    - dev
    - /^version-[0-9]+[.][0-9]+([.][0-9]+)?$/
  script: [ "./gradlew check publish -PgenerateTestCases" ]

dependency-check:
  extends: .setup
  stage: dependency-check
  interruptible: true
  only:
    variables:
      - $RUN_DEPENDENCY_CHECK == "true"
  script: [ "./gradlew dependencyCheckAggregate" ]
  artifacts:
    when: always
    paths: [ build/reports/dependency-check-report.* ]
