image: registry.gitlab.com/chromaway/core-tools/chromia-images/maven-docker-java21:1.0.5@sha256:263fc66ab6ed7b3ee9afbd3726c6ea65dc16e186d41fee2b1844bcad71f7f864

stages:
  - build
  - deploy
  - dependency-check

variables:
  GRADLE_USER_HOME: "$CI_PROJECT_DIR/.gradle"
  GRADLE_OPTS: "-Dorg.gradle.caching=true"
  POSTCHAIN_DB_URL: jdbc:postgresql://docker/postchain
  DOCKER_HOST: tcp://docker:2375
  JACOCO_REPORT_DIR: coverage-report-aggregate/build/reports/jacoco/testCodeCoverageReport

services:
  - name: docker:23.0.4-dind
    alias: docker
    command: [ "--tls=false" , "--experimental" ]

cache:
  key: "$CI_COMMIT_REF_SLUG"
  fallback_keys:
    - dev
  paths:
    - .gradle
  policy: pull-push

.setup:
  tags: [ saas-linux-large-amd64 ]
  before_script:
    - docker run
      --detach
      --name postgres
      --env POSTGRES_PASSWORD=postchain
      --env POSTGRES_USER=postchain
      --env PGDATA=/pgtmpfs
      --tmpfs=/pgtmpfs:size=1000m
      --publish 5432:5432
      postgres:16.6-alpine3.21@sha256:aba1fab94626cf8b0f4549055214239a37e0a690f03f142b7bca05b9ed36c6db
    - chmod +x gradlew
    - ./gradlew --version
  artifacts:
    when: always
    paths:
      - $JACOCO_REPORT_DIR/*
      - "**/build/test-results/**/*"
    reports:
      junit: [ "**/build/test-results/**/TEST-*.xml" ]
      coverage_report:
        coverage_format: jacoco
        path: "**/build/reports/jacoco/test/jacocoTestReport.xml"
    expire_in: 1 week

build:
  extends: .setup
  stage: build
  except:
    - master
    - dev
    - /^version-[0-9]+[.][0-9]+([.][0-9]+)?$/
  script: [ "./gradlew check :coverage-report-aggregate:testCodeCoverageReport" ]

deploy:
  extends: .setup
  stage: deploy
  only:
    - master
    - dev
    - /^version-[0-9]+[.][0-9]+([.][0-9]+)?$/
  script: [ "./gradlew check publish -PgenerateTestCases" ]

dependency-check:
  extends: .setup
  stage: dependency-check
  interruptible: true
  only:
    variables:
      - $RUN_DEPENDENCY_CHECK == "true"
  script: [ "./gradlew dependencyCheckAggregate" ]
  artifacts:
    when: always
    paths: [ build/reports/dependency-check-report.* ]
