/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("net.postchain.rell.codegen.kotlin-library-conventions")
}
repositories {
    mavenCentral()
    maven("https://gitlab.com/api/v4/projects/32294340/packages/maven")
    maven("https://gitlab.com/api/v4/projects/32802097/packages/maven")
    maven("https://jcenter.bintray.com")
    maven("https://maven.emrld.io")
}

dependencies {
    implementation(project(":codegen"))
    implementation("net.postchain.rell:rell:0.10.10")
    testImplementation("org.jetbrains.kotlin:kotlin-compiler-embeddable")
}
