package net.postchain.rell.codegen.kotlin

import net.postchain.rell.codegen.document.AbstractDocument

class KotlinDocument(packageString: String) : AbstractDocument(
    "// Generated by kotlin generator",
    packageString
) {
}