package net.postchain.rell.codegen.kotlin

import net.postchain.rell.codegen.document.AbstractDocument

class KotlinDocument(packageName: String) : AbstractDocument(
    "// Generated by kotlin generator",
    "package $packageName"
) {
}