package net.postchain.rell.codegen.kotlin

import net.postchain.rell.codegen.deps.ClassName
import net.postchain.rell.codegen.document.AbstractDocument

class KotlinDocument(val packageName: String, moduleName: String) : AbstractDocument(
    "// Generated by kotlin generator",
    moduleName
) {
    override fun formatPackageString() =
        if (module.isBlank()) "package $packageName" else "package $packageName.$module"
    override fun formatImportString(className: ClassName) = "import ${className.toPackageName(packageName)}"
}
