package net.postchain.rell.codegen.kotlin

import net.postchain.rell.codegen.document.AbstractDocument

class KotlinDocument(packageName: String, moduleName: String) : AbstractDocument(
    "// Generated by kotlin generator",
    formatPackageString(packageName, moduleName)
) {
}

private fun formatPackageString(packageName: String, moduleName: String) =
    if (moduleName.isBlank()) "package $packageName" else "package $packageName.$moduleName"