/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("net.postchain.rell.codegen.kotlin-library-conventions")
}
repositories {
    mavenCentral()
    maven("https://gitlab.com/api/v4/projects/32294340/packages/maven")
    maven("https://gitlab.com/api/v4/projects/32802097/packages/maven")
    maven("https://jcenter.bintray.com")
    maven("https://maven.emrld.io")
}

dependencies {
    implementation(project(":codegen"))
    implementation("net.postchain.rell:rell:0.11.0")
    implementation("net.postchain:postchain-common:3.7.0")
    implementation("net.postchain:postchain-client:3.7.0")
    implementation("net.postchain:postchain-gtv:3.7.0")
    testImplementation("org.jetbrains.kotlin:kotlin-compiler-embeddable")
    testImplementation(project(":codegen", "testConfiguration"))
}

val copy by tasks.register<Copy>("copy-resources") {
    from("${rootProject.rootDir}/testResources")
    into("${project.buildDir}/resources/test")
}

val test by tasks.getting {
    dependsOn(copy)
}