/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package net.postchain.rell.codegen.app

import com.github.ajalt.clikt.core.NoOpCliktCommand
import com.github.ajalt.clikt.core.subcommands

class RellCodegen : NoOpCliktCommand("Rell code generator")

fun main(args: Array<String>) = RellCodegen().subcommands(
    KotlinCommand()
).main(args)
