/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("net.postchain.rell.codegen.kotlin-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":codegen"))
    implementation(project(":kotlin-codegen"))
    implementation("com.github.ajalt.clikt:clikt:3.4.0")
}

application {
    // Define the main class for the application.
    mainClass.set("net.postchain.rell.codegen.app.AppKt")
}
