package net.postchain.rell.codegen.typescript

import net.postchain.rell.codegen.deps.ClassName
import net.postchain.rell.codegen.document.AbstractDocument

class TypescriptDocument(val packageName: String, moduleName: String) : AbstractDocument(
        "// Generated by typescript generator",
        moduleName
) {
    override fun formatPackageString() = ""

    override fun formatImportString(className: ClassName) = ""

    override fun format(): String {
        return """
            |$intro
            |${collectImports().sorted().joinToString("\n")}
            |
            |${sections.joinToString("\n") { it.format()}}
        """.trimMargin()
    }
}
