# Generated by python generator


from dataclasses import dataclass
from enum import Enum
from postchain_client_py.blockchain_client.types import Operation
from postchain_client_py.blockchain_client.types import QueryObject
from postchain_client_py.utils.gtv import RawGtv
from postchain_client_py.utils.types import BigInt
from typing import Dict, Any, List, Set, Optional

class TestEnum(Enum):
	A = "a"

class MyNs1LocalTestEnum(Enum):
	A = "a"


@dataclass(frozen=True)
class TestStruct:
	a: bool

	def to_dict(self) -> Dict[str, Any]:
		"""Create a dictionary representation of the object"""
		return {"a": self.a}

	@classmethod
	def from_dict(cls, data: Dict[str, Any]) -> 'TestStruct':
		"""Create an object from a dictionary"""
		return cls(data["a"])


@dataclass(frozen=True)
class MyNs1TestStruct2:
	name: str

	def to_dict(self) -> Dict[str, Any]:
		"""Create a dictionary representation of the object"""
		return {"name": self.name}

	@classmethod
	def from_dict(cls, data: Dict[str, Any]) -> 'MyNs1TestStruct2':
		"""Create an object from a dictionary"""
		return cls(data["name"])


@dataclass(frozen=True)
class MyNs1LocalTestStruct:
	a: bool

	def to_dict(self) -> Dict[str, Any]:
		"""Create a dictionary representation of the object"""
		return {"a": self.a}

	@classmethod
	def from_dict(cls, data: Dict[str, Any]) -> 'MyNs1LocalTestStruct':
		"""Create an object from a dictionary"""
		return cls(data["a"])


@dataclass(frozen=True)
class MyNs1MyNs12TestStruct2:
	a: bool

	def to_dict(self) -> Dict[str, Any]:
		"""Create a dictionary representation of the object"""
		return {"a": self.a}

	@classmethod
	def from_dict(cls, data: Dict[str, Any]) -> 'MyNs1MyNs12TestStruct2':
		"""Create an object from a dictionary"""
		return cls(data["a"])


def return_type_enum() -> QueryObject:
	return QueryObject(name="return_type_enum", args={})


def return_type_boolean() -> QueryObject:
	return QueryObject(name="return_type_boolean", args={})


def return_type_integer() -> QueryObject:
	return QueryObject(name="return_type_integer", args={})


def return_type_big_integer() -> QueryObject:
	return QueryObject(name="return_type_big_integer", args={})


def return_type_text() -> QueryObject:
	return QueryObject(name="return_type_text", args={})


def return_type_decimal() -> QueryObject:
	return QueryObject(name="return_type_decimal", args={})


def return_type_byte_array() -> QueryObject:
	return QueryObject(name="return_type_byte_array", args={})


def return_type_pubkey() -> QueryObject:
	return QueryObject(name="return_type_pubkey", args={})


def return_type_entity() -> QueryObject:
	return QueryObject(name="return_type_entity", args={})


def return_type_nullable_entity() -> QueryObject:
	return QueryObject(name="return_type_nullable_entity", args={})


def return_type_struct() -> QueryObject:
	return QueryObject(name="return_type_struct", args={})


def return_type_rowid() -> QueryObject:
	return QueryObject(name="return_type_rowid", args={})


def return_type_nullable_rowid() -> QueryObject:
	return QueryObject(name="return_type_nullable_rowid", args={})


def return_type_gtv() -> QueryObject:
	return QueryObject(name="return_type_gtv", args={})


def return_type_nullable_gtv() -> QueryObject:
	return QueryObject(name="return_type_nullable_gtv", args={})


def return_type_list_integer() -> QueryObject:
	return QueryObject(name="return_type_list_integer", args={})


def return_type_list_boolean() -> QueryObject:
	return QueryObject(name="return_type_list_boolean", args={})


def return_type_list_byte_array() -> QueryObject:
	return QueryObject(name="return_type_list_byte_array", args={})


def return_type_set_integer() -> QueryObject:
	return QueryObject(name="return_type_set_integer", args={})


def return_type_list_struct() -> QueryObject:
	return QueryObject(name="return_type_list_struct", args={})


def return_type_nullable_list_struct() -> QueryObject:
	return QueryObject(name="return_type_nullable_list_struct", args={})


def return_type_list_entity() -> QueryObject:
	return QueryObject(name="return_type_list_entity", args={})


def return_type_nullable_list_entity() -> QueryObject:
	return QueryObject(name="return_type_nullable_list_entity", args={})


def return_type_list_gtv() -> QueryObject:
	return QueryObject(name="return_type_list_gtv", args={})


def return_type_list_list_list() -> QueryObject:
	return QueryObject(name="return_type_list_list_list", args={})


def return_type_set_gtv() -> QueryObject:
	return QueryObject(name="return_type_set_gtv", args={})


def return_type_map() -> QueryObject:
	return QueryObject(name="return_type_map", args={})


def return_type_nullable_map() -> QueryObject:
	return QueryObject(name="return_type_nullable_map", args={})


def return_type_enum_map() -> QueryObject:
	return QueryObject(name="return_type_enum_map", args={})


def return_type_nullable_enum_map() -> QueryObject:
	return QueryObject(name="return_type_nullable_enum_map", args={})


def return_type_any_map() -> QueryObject:
	return QueryObject(name="return_type_any_map", args={})


def return_type_named_tuple() -> QueryObject:
	return QueryObject(name="return_type_named_tuple", args={})


def return_type_nullable_named_tuple() -> QueryObject:
	return QueryObject(name="return_type_nullable_named_tuple", args={})


def return_type_named_tuple_list(since: int) -> QueryObject:
	return QueryObject(name="return_type_named_tuple_list", args={"since": since})


def return_type_unnamed_tuple() -> QueryObject:
	return QueryObject(name="return_type_unnamed_tuple", args={})


def return_type_proposals_since(since: int) -> QueryObject:
	return QueryObject(name="return_type_proposals_since", args={"since": since})


def input_parameter_nargs() -> QueryObject:
	return QueryObject(name="input_parameter_nargs", args={})


def input_parameter_text(t: str) -> QueryObject:
	return QueryObject(name="input_parameter_text", args={"t": t})


def input_parameter_nullable(t: Optional[str]) -> QueryObject:
	return QueryObject(name="input_parameter_nullable", args={"t": t})


def input_parameter_enum(e: TestEnum) -> QueryObject:
	return QueryObject(name="input_parameter_enum", args={"e": e.value})


def input_parameter_integer(i: int) -> QueryObject:
	return QueryObject(name="input_parameter_integer", args={"i": i})


def input_parameter_big_integer(i: BigInt) -> QueryObject:
	return QueryObject(name="input_parameter_big_integer", args={"i": i})


def input_parameter_boolean(b: bool) -> QueryObject:
	return QueryObject(name="input_parameter_boolean", args={"b": b})


def input_parameter_rowid(r: int) -> QueryObject:
	return QueryObject(name="input_parameter_rowid", args={"r": r})


def input_parameter_pubkey(pubkey: bytes) -> QueryObject:
	return QueryObject(name="input_parameter_pubkey", args={"pubkey": pubkey})


def input_parameter_blockchain_rid(blockchain_rid: bytes) -> QueryObject:
	return QueryObject(name="input_parameter_blockchain_rid", args={"blockchain_rid": blockchain_rid})


def input_parameter_entity(e: int) -> QueryObject:
	return QueryObject(name="input_parameter_entity", args={"e": e})


def input_parameter_struct(s: TestStruct) -> QueryObject:
	return QueryObject(name="input_parameter_struct", args={"s": s.to_dict()})


def input_parameter_list_input(v: List[bytes]) -> QueryObject:
	return QueryObject(name="input_parameter_list_input", args={"v": v})


def input_parameter_nullable_list_input(v: Optional[List[bytes]]) -> QueryObject:
	return QueryObject(name="input_parameter_nullable_list_input", args={"v": v if v else None})


def input_parameter_set_input(v: Set[bytes]) -> QueryObject:
	return QueryObject(name="input_parameter_set_input", args={"v": list(v)})


def input_parameter_map_input(v: Dict[str, bytes]) -> QueryObject:
	return QueryObject(name="input_parameter_map_input", args={"v": {k: v for k, v in v.items()}})


def input_parameter_enum_map(m: Dict[TestEnum, bytes]) -> QueryObject:
	return QueryObject(name="input_parameter_enum_map", args={"m": [[k.value, v] for k, v in m.items()]})


def input_parameter_any_map(m: Dict[TestStruct, bytes]) -> QueryObject:
	return QueryObject(name="input_parameter_any_map", args={"m": [[k.to_dict(), v] for k, v in m.items()]})


def input_parameter_multiple(s: str, s2: str) -> QueryObject:
	return QueryObject(name="input_parameter_multiple", args={"s": s, "s2": s2})


def input_parameter_gtv(g: RawGtv) -> QueryObject:
	return QueryObject(name="input_parameter_gtv", args={"g": g})


def input_parameter_nullable_gtv(g: Optional[RawGtv]) -> QueryObject:
	return QueryObject(name="input_parameter_nullable_gtv", args={"g": g})


def my_ns1_q1_in_namespace(e: TestEnum) -> QueryObject:
	return QueryObject(name="my_ns1.q1_in_namespace", args={"e": e.value})


def my_ns1_q2_in_namespace(s: MyNs1TestStruct2) -> QueryObject:
	return QueryObject(name="my_ns1.q2_in_namespace", args={"s": s.to_dict()})


def my_ns1_q3a_return_type_enum(e: MyNs1LocalTestEnum) -> QueryObject:
	return QueryObject(name="my_ns1.q3a_return_type_enum", args={"e": e.value})


def my_ns1_q3b_return_type_enum(m: Dict[TestEnum, bytes]) -> QueryObject:
	return QueryObject(name="my_ns1.q3b_return_type_enum", args={"m": [[k.value, v] for k, v in m.items()]})


def my_ns1_q4_return_type_list_struct(m: Dict[bytes, MyNs1MyNs12TestStruct2]) -> QueryObject:
	return QueryObject(name="my_ns1.q4_return_type_list_struct", args={"m": [[k, v.to_dict()] for k, v in m.items()]})


def my_ns1_q5_return_type_list_struct(v: List[MyNs1LocalTestStruct]) -> QueryObject:
	return QueryObject(name="my_ns1.q5_return_type_list_struct", args={"v": [item.to_dict() for item in v]})


def my_ns1_q6_return_type_list_struct() -> QueryObject:
	return QueryObject(name="my_ns1.q6_return_type_list_struct", args={})


def my_ns1_q7_return_type_enum_map() -> QueryObject:
	return QueryObject(name="my_ns1.q7_return_type_enum_map", args={})


def my_ns1_q8_return_type_enum_map() -> QueryObject:
	return QueryObject(name="my_ns1.q8_return_type_enum_map", args={})


def my_ns1_q9_return_type_any_map() -> QueryObject:
	return QueryObject(name="my_ns1.q9_return_type_any_map", args={})


def my_ns1_q10_return_type_any_map() -> QueryObject:
	return QueryObject(name="my_ns1.q10_return_type_any_map", args={})


def my_ns1_my_ns2_q2_in_namespace() -> QueryObject:
	return QueryObject(name="my_ns1.my_ns2.q2_in_namespace", args={})


def my_ns1_my_ns2_q_3_in_namespace() -> QueryObject:
	return QueryObject(name="my_ns1.my_ns2.q_3_in_namespace", args={})


def before_query_test_operation() -> Operation:
	return Operation(op_name="before_query_test", args=[])
