package net.postchain.rell.codegen.python

import net.postchain.rell.codegen.deps.ClassName
import net.postchain.rell.codegen.document.AbstractDocument

class PythonDocument(moduleName: String) : AbstractDocument(
    "# Generated by python generator",
    moduleName
) {
    override fun formatPackageString() = ""

    override fun formatImportString(className: ClassName): String {
        val targetModule = className.module.takeIf { it.isNotBlank() } ?: "root"

        val currentParts = module.split(".").filter { it.isNotEmpty() }
        val targetParts = targetModule.split(".").filter { it.isNotEmpty() }

        val shared = (currentParts zip targetParts)
            .takeWhile { (current, target) ->
                current == target
            }.size

        val upLevels = currentParts.size - shared
        val downParts = targetParts.drop(shared)

        val relativePart = when (upLevels) {
            0 -> ""
            1 -> "."
            else -> ".".repeat(upLevels)
        }

        val modulePath = if (targetModule == "root") {
            "root"
        } else {downParts.joinToString(".") {
                it.replace(Regex("\\W+"), "_")
            }
        }

        val fullModulePath = listOf(relativePart, modulePath)
            .filter { it.isNotEmpty() }
            .joinToString(".")

        val identifier = if (targetModule == "root") "" else targetParts.joinToString("_") {
            it.replace(Regex("\\W+"), "")
        }

        return buildString {
            append("from $fullModulePath")
            if (identifier.isNotEmpty()) append(".$identifier")
            append(" import ${className.className}")
        }
    }
}