package net.postchain.rell.codegen.python

import net.postchain.rell.codegen.deps.ClassName
import net.postchain.rell.codegen.document.AbstractDocument

class PythonDocument(moduleName: String) : AbstractDocument(
    "# Generated by python generator",
    moduleName
) {
    override fun formatPackageString() = ""

    override fun formatImportString(className: ClassName) = /*TODO */ "// <Import>"
}